# Header
menu:
  首页: /
  项目: /stories
  关于: /about

# Content
excerpt_link: 阅读全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /images/favicon.ico
webclip: /images/webclip
brand:   /images/brand.svg

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/banner/personal-banner.svg
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: 平景龙 · Jinglong Ping
  secondary: 数据科学与空间规划｜城市交通、空间数据与乡村发展
  archives: 文章与动态
  pages: Data Science × Spatial Planning
  posts: 用数据工程和计算方法理解城市、交通与乡村空间

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js
